export const firstTeamName = document.getElementById("teamName1")
export const secondTeamName = document.getElementById("teamName2")
export const score = document.getElementById("score")
export const homeTeamLogo = document.getElementById("logo1")
export const awayTeamLogo = document.getElementById("logo2")
export const nextMatch = document.getElementById("nextMatch")
export const previousMatch = document.getElementById("previousMatch")

export const time = document.getElementById("time")
export const events = document.querySelector(".events")
export const footballEvents = document.getElementById("footballEvents")